//#define CONFIG_TEST_TTY
#define CONFIG_TEST_FONT
//#define CONFIG_TEST_INT
//#define CONFIG_TEST_DIV
//#define CONFIG_TEST_SCANCODES
//#define CONFIG_LINES_50
#define VGA_ATTRIBUTE 0x70
#define VGA_STATUS_ATTRIBUTE 0x2F

