#ifndef GDT_H
#define GDT_H

#define GDT_KERN_CODE 1
#define __KERN_CS               (GDT_KERN_CODE * 8)

#define GDT_KERN_DATA 2
#define __KERN_DS               (GDT_KERN_DATA * 8)


#define FLAGS0_PRESENT 0x90

#define FLAGS0_DPL_0 0x00
#define FLAGS0_DPL_1 0x20
#define FLAGS0_DPL_2 0x40
#define FLAGS0_DPL_3 0x60

#define FLAGS0_PERM_RW 0x02
#define FLAGS0_PERM_DC 0x04
#define FLAGS0_PERM_EX 0x08

#define FLAGS0_KERN_CODE (FLAGS0_PRESENT | FLAGS0_DPL_0 | FLAGS0_PERM_EX | FLAGS0_PERM_RW)
#define FLAGS0_KERN_DATA (FLAGS0_PRESENT | FLAGS0_DPL_0 | FLAGS0_PERM_RW)


#define FLAGS1_GRANULARITY_PAGE 0x80
#define FLAGS1_GRANULARITY_BYTE 0x00
#define FLAGS1_SIZE_32 0x40
#define FLAGS1_SIZE_16 0x00

#define FLAGS1_KERN (FLAGS1_GRANULARITY_PAGE | FLAGS1_SIZE_32)

#endif

